//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestoin
    {
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Correct { get; set; }
        public int ID { get; set; }
    }
}
