//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationUR
    {
        public int UserID { get; set; }
        public int PK_R { get; set; }
        public int RoleID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Role Role { get; set; }
    }
}
