//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamForm
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SLoginInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SLoginInfo()
        {
            this.Enrolls = new HashSet<Enroll>();
        }
    
        public int StudentID { get; set; }
        public string UserName { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public Nullable<System.DateTime> LastLoginDate { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public Nullable<int> LoginFailedCount { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public string LoginIPAddress { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public string StudentTimeZone { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public Nullable<System.DateTime> LastAccessedDate { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public Nullable<bool> AccountLocked { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public Nullable<int> UserResult { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public string Password { get; set; }

        [DisplayFormat(NullDisplayText = "Never Used")]
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enrolls { get; set; }
        public virtual User User { get; set; }
    }
}
